### ISSUE TITLE
4月更新计划

### ISSUE THREAD

**Issue by DrOmega9834** [Dr-Omega9834/Asphalt9#2]
* 多人脚本预计清明节后上线
* 完善的多功能脚本预计4月中下旬上线
* 多功能将包括
  * 生涯
  * 每日赛事
      * 暂时只会打那个1票的*每日车辆战利品*
      * 是否 实时更新 新的杯赛取决于大家的热情了（点Star，赞助作者之类的#(滑稽)）
  * 多人

**Comment by sol1618** [comment]
加油大佬，一直用你的脚本，万分感谢。另外有个问题请教一下，我的三星A9，安卓6.0的系统，1920*1080的分辨率，选关会选到13关，然后就卡死不走了，另一台手机三星S9+ 2220×1080的分辨率正常使用

**Comment by DrOmega9834** [comment]
> 加油大佬，一直用你的脚本，万分感谢。另外有个问题请教一下，我的三星A9，安卓6.0的系统，1920*1080的分辨率，选关会选到13关，然后就卡死不走了，另一台手机三星S9+ 2220×1080的分辨率正常使用

不好意思 现在暂时不支持Android 6.0

**Comment by DrOmega9834** [comment]
多人脚本已经上传，稍后更新readme.md

**Comment by yaodao0yaodao** [comment]
大佬666

**Comment by yaodao0yaodao** [comment]
等待readme.md，那么多js不知道运行哪个

**Comment by yaodao0yaodao** [comment]
跑多人，刷声望，运行哪个js 啊

**Comment by DrOmega9834** [comment]
@yaodao0yaodao 使用说明已上传

**Comment by sol1618** [comment]
多人赛怎么识别经典多人和限定赛？不论选哪一个，都会返回主页并提示是否退出游戏，脚本还没有完善吗？

**Comment by DrOmega9834** [comment]
> 多人赛怎么识别经典多人和限定赛？

* 在哪个多人的开始界面开始运行脚本就默认挂哪个多人，然后如果是在游戏的主界面运行就挂两个多人中靠上面的那个

> 不论选哪一个，都会返回主页并提示是否退出游戏，脚本还没有完善吗？

* 您的手机分辨率是2220 × 1080，暂时不支持的呢

**Comment by sol1618** [comment]
难怪，以前旧版支持好几个分辨率，现在只支持1920*1080了吗？是因为全部修改工作量比较大吗

**Comment by DrOmega9834** [comment]
您的猜想是正确的，由于多人脚本的原因，多分辨率全部改一遍太麻烦了

**Comment by LifetruthForgotten** [comment]
说明文档中的“截图示例”下载后却是代码，希望大佬能出一个教程怎样自己适配分辨率，对于代码中的一些地方我不是很明白

**Comment by LifetruthForgotten** [comment]
您好，本人手机分辨率是2040*1080的，想自己适配分辨率，但是有几个地方不是很清楚希望大佬可以解答一下
1.多人块这个地方是不是指选择多人赛的界面，如果我把这个坐标改为限时赛是不是默认循环限时赛
2.我看上面说默认在哪个界面运行就默认挂哪个多人，但领奖时将会回到选择赛事的界面，而多人块的坐标为经典赛，那么在限时赛领奖之后会不会改为经典赛继续循环
3.车辆间距是否指的是：1号车上边框与2号车上边框的距离为Y，1号车左边框与3号车左边框的距离为X

**Comment by DrOmega9834** [comment]
> 您好，本人手机分辨率是2040*1080的，想自己适配分辨率，但是有几个地方不是很清楚希望大佬可以解答一下
> 1.多人块这个地方是不是指选择多人赛的界面，如果我把这个坐标改为限时赛是不是默认循环限时赛
> 2.我看上面说默认在哪个界面运行就默认挂哪个多人，但领奖时将会回到选择赛事的界面，而多人块的坐标为经典赛，那么在限时赛领奖之后会不会改为经典赛继续循环
> 3.车辆间距是否指的是：1号车上边框与2号车上边框的距离为Y，1号车左边框与3号车左边框的距离为X

1. 多人块其实指的是主界面底部的导航栏，只是GL的策略是只点击那个导航栏的多人块会默认进入靠上方的那个多人
2. 这个你可以试试
3. 嗯，但是实际我自己取点取得不是边框。因为边框放大看颜色是渐变的，没有一个合理的参照物用于定位

**Comment by LifetruthForgotten** [comment]
![Screenshot_2019-05-01-13-39-02-590_com gameloft a](https://user-images.githubusercontent.com/28033474/57007168-358e2100-6c19-11e9-8bf5-7f464f0a57c6.png)
您好，我在运行脚本时报错是为什么呢

**Comment by LifetruthForgotten** [comment]
方便加下联系方式吗，我有些问题想要请教下，我qq723897428
