### ISSUE TITLE
autojs下载挂了

### ISSUE THREAD

**Issue by Anniversor** [Dr-Omega9834/Asphalt9#9]
autojs的github releases被删了...求大大给个下载的地方啊...

**Comment by DrOmega9834** [comment]
收到 明天来补链接

**Comment by DrOmega9834** [comment]
[Auto.js.zip](https://github.com/Dr-Omega9834/Asphalt9/files/3417174/Auto.js.zip)
把zip后缀改为apk就好了

**Comment by Anniversor** [comment]
感谢老铁
